coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: 60%
        threshold: 5%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "meshing_around_clients/tui/app.py"
  - "meshing_around_clients/tui/whiptail_tui.py"
  - "tests/**/*"
